[0m[[0m[31merror[0m] [0m[0mC:\Users\DIOP028957\IdeaProjects\Pe_minirun\src\main\scala\IngestionsPe.scala:56:24: reference to dailyClients is ambiguous;[0m
[0m[[0m[31merror[0m] [0m[0mit is imported twice in the same scope by[0m
[0m[[0m[31merror[0m] [0m[0mimport fonctions.multi_sim._[0m
[0m[[0m[31merror[0m] [0m[0mand import fonctions.utils._[0m
[0m[[0m[31merror[0m] [0m[0m      val df_clients = dailyClients(base_clients, table_anonym_kibaru, "20240515")[0m
[0m[[0m[31merror[0m] [0m[0m                       ^[0m
[0m[[0m[31merror[0m] [0m[0mC:\Users\DIOP028957\IdeaProjects\Pe_minirun\src\main\scala\IngestionsPe.scala:65:37: reference to dailyClients is ambiguous;[0m
[0m[[0m[31merror[0m] [0m[0mit is imported twice in the same scope by[0m
[0m[[0m[31merror[0m] [0m[0mimport fonctions.multi_sim._[0m
[0m[[0m[31merror[0m] [0m[0mand import fonctions.utils._[0m
[0m[[0m[31merror[0m] [0m[0m      val daily_clients_df        = dailyClients      (table_daily_clients         ,             fin)[0m
[0m[[0m[31merror[0m] [0m[0m                                    ^[0m
[0m[[0m[31merror[0m] [0m[0mtwo errors found[0m
